
export default { 
    LOGIN_REC_CREATE_SUCCESS: 'LOGIN_REC_CREATE_SUCCESS',
    LOGIN_REC_CREATE_FAILURE: 'LOGIN_REC_CREATE_FAILURE',
    LOGIN_REC_LOGIN_SUCCESS: 'LOGIN_REC_LOGIN_SUCCESS',
    LOGIN_REC_LOGIN_FAILURE: 'LOGIN_REC_LOGIN_FAILURE',
    LOGIN_REC_LOGOUT_SUCCESS: 'LOGIN_REC_LOGOUT_SUCCESS',
    LOGIN_REC_LOGOUT_FAILURE: 'LOGIN_REC_LOGOUT_FAILURE',
    LEDGER_REC_BALANCE_SUCCESS: 'LEDGER_REC_BALANCE_SUCCESS',
    LEDGER_REC_BALANCE_FAILURE: 'LEDGER_REC_BALANCE_FAILURE',
    LEDGER_REC_HISTORY_SUCCESS: 'LEDGER_REC_HISTORY_SUCCESS',
    LEDGER_REC_HISTORY_FAILURE: 'LEDGER_REC_HISTORY_FAILURE',
    LEDGER_REC_DEPOSIT_SUCCESS: 'LEDGER_REC_DEPOSIT_SUCCESS',
    LEDGER_REC_DEPOSIT_FAILURE: 'LEDGER_REC_DEPOSIT_FAILURE',
    LEDGER_REC_WITHDRAWL_SUCCESS: 'LEDGER_REC_WITHDRAWL_SUCCESS',
    LEDGER_REC_WITHDRAWL_FAILURE: 'LEDGER_REC_WITHDRAWL_FAILURE'
 };